name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: CheckoutCode
      uses: actions/checkout@v4
      with:
          fetch-depth: 0
    - name: Docker login
      env:
          DOCKER_USER: ${{ secrets.DOCKER_USER }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: |
        echo "Iniciando Login"
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
        echo "Fin del Login"
        
    - name: Build Docker Image
      run: |
        docker build -t julianr9230/docker-graphql:0.0.1 .
        docker build -t julianr9230/docker-graphql:latest .
        
    - name: Push docker Image
      run: |
        docker push julianr9230/docker-graphql:0.0.1
        docker push julianr9230/docker-graphql:latest
        
     
        
        
        
          
    
    # - name: Build the Docker image
    #   run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
